name: highcharts_flutter
version: 1.2.0
description: >-
  Official Flutter integration for Highcharts with many options for interactive
  charts, that can be adjusted and dynamically loaded.
homepage: https://www.highcharts.com/integrations/
issue_tracker: https://github.com/highcharts/highcharts_flutter/issues
repository: https://github.com/highcharts/highcharts_flutter

platforms:
  android:
  ios:
  web:
  #linux:
  #macos:
  #windows:

topics:
  - charts
  - diagrams
  - graphs
  - webview

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  highcharts_flutter_webwebview: ^0.3.5
  provider: ^6.1.2
  web: ^1.1.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.2
  webview_flutter_wkwebview: ^3.16.2
  http: ^1.4.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  webview_flutter_platform_interface: ^2.13.1

flutter:
  assets:
    - assets/highcharts_flutter.js
    - assets/highcharts_view.html
    - assets/highcharts/
    - assets/highcharts/indicators/
    - assets/highcharts/modules/
